# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 05:21
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=fernet_fields.fields.EncryptedTextField(null=True),
        ),
    ]
