# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 05:21
from __future__ import unicode_literals

from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180831_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_phone_number',
            field=server.models.PhoneEncryptedField(blank=True, max_length=128, null=True),
        ),
    ]
